### ISSUE TITLE
Contact info

### ISSUE THREAD

**Issue by Sarthakpurii** [Miloas/homebrew-zig-nightly#1]
Hey Miloas,

Can i get your any contact info, preferably mail or linkedin. I'm currently developing a script for LeetCode and came across your work on the vscode-Leetcode project and wanted to seek some guidance from you.

Warm regards,
Sarthak Puri
sarthak.00puri@gmail.com

**Comment by Miloas** [comment]
Hi, sorry. I am not the LeetCode/vscode-leetcode maintainer now.
